# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/SentenceGraph',
                'doc_host': 'https://Hevia.github.io',
                'git_url': 'https://github.com/Hevia/SentenceGraph',
                'lib_path': 'SentenceGraph'},
  'syms': {'SentenceGraph.core': {'SentenceGraph.core.foo': ('core.html#foo', 'SentenceGraph/core.py')}}}